// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { ApiRouteMethodMap, RouteLoaderData, RouteParamInput, SearchParamsInput } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    routes: {
      "home": {
        path: "/";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/home")>;
      };
      "book": {
        path: "/:id";
        params: { "id": RouteParamInput; };
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/book")>;
      };
    };
    apiRoutes: {
      "/api/_pracht/image": {
        path: "/api/_pracht/image";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/_pracht/image")>;
      };
    };
  }
}

export {};
